### ISSUE TITLE
Publish shiny app or add screenshot to readme

### ISSUE THREAD

**Issue by HeidiSeibold** [OpenDataDayZurich2016/ODDPredictDelays#9]
Just so we can see, what the output of the project is, without having to run the code.

Thanks :) :cake:

**Comment by lorenzwalthert** [comment]
ok, I can do that

**Comment by lorenzwalthert** [comment]
ok, check out this link for the [deployed version](https://lorenzwalthert.shinyapps.io/odd_predict_delays/)  of the app. Thanks @rstudio for hosting for free 😊

**Comment by HeidiSeibold** [comment]
Added a comment to your readme to link to this. Hope this is ok for you :)
